### ISSUE TITLE
fail to load vgg-model

### ISSUE THREAD

**Issue by yunkaili** [bengxy/FastNeuralStyle#1]
i am trying to load the vgg16 model
however, it seems not work

here is some information i got from system

Traceback (most recent call last):
  File "train_philm.py", line 54, in <module>
    utils.init_vgg16()
  File "/home/liyunkai/program/pytorch/FastNeuralStyle/utils.py", line 17, in init_vgg16
    dst[:] = src[:]
  File "/home/liyunkai/local/anaconda2/lib/python2.7/site-packages/torch/autograd/variable.py", line 82, in __setitem__
    return SetItem(key, value)(self)
RuntimeError: a leaf Variable that requires grad has been used in an in-place operation.

Has anyone run this project successfully?

**Comment by bengxy** [comment]
Thank you!    And Bug fixed.
I change code in `utils.py` 
```
dst[:] = src[:]
to
dst[:].data = src[:]
```

**Here is the reason:**
type of src[:] is  `torch.FloatTensor`
type of dst[:] is `torch.autograd.variable.Variable`

**After pytorch version 0.1.10
assign a `torch.FloatTensor` to `torch.autograd.variable.Variable` is not allowed.**

So we need to use

```
dst[:].data = src[:]
```

**Also,new code is runnable in previous version of pytorch.**
