### ISSUE TITLE
Better to release the pretrained model

### ISSUE THREAD

**Issue by zeakey** [bengxy/FastNeuralStyle#2]
It's better to release the pretrained model.

**Comment by bengxy** [comment]
Sorry, I‘m in internship and will release the pre-trained model later ...

**Comment by bengxy** [comment]
Now I have released a pretrained model, which use the style [wave](https://github.com/bengxy/FastNeuralStyle/blob/master/images/wave.jpg)
[wave.model](https://cloud.bengxy.com/index.php/s/QF1ZYEBgTVoPzqV)

more pretrained models will release soon.
